//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by w3dview.rc
//
#define IDD_ABOUT                       100
#define IDD_MESH                        106
#define IDD_EMITTER                     107
#define IDR_MAINFRAME                   128
#define IDD_COLORPICKER                 129
#define IDI_DOCUMENT                    129
#define IDB_MARKER                      130
#define IDB_KEYFRAME                    131
#define IDC_MOVE                        131
#define IDB_KEYFRAMEVERT                132
#define IDC_ZOOM                        132
#define IDR_LODMENU                     135
#define IDD_ANIMSETTINGS                136
#define IDR_ANIMATIONMENU               136
#define IDI_ANIMATION                   137
#define IDR_HIERARCHYMENU               137
#define IDI_MESH                        138
#define IDD_AMBIENT                     139
#define IDI_MATERIAL                    139
#define IDI_HIERARCHY                   140
#define IDD_DEVICESELECTION             140
#define IDD_HIERARCHY                   141
#define IDI_HLOD                        141
#define IDD_SCENELIGHT                  142
#define IDD_BGCOLOR                     143
#define IDD_BACKGROUNDOBJECT            146
#define IDD_ANIMATION                   147
#define IDD_BACKGROUNDBITMAP            148
#define IDD_EMITTERPARTICLE             149
#define IDD_EMITTERPHYS                 150
#define IDB_XDIR                        150
#define IDI_USER                        150
#define IDD_EMITTERCOLOR                151
#define IDI_PHYSICS                     151
#define IDD_EMITTERUSER                 152
#define IDB_YDIR                        152
#define IDI_EMISSION                    152
#define IDB_ZDIR                        153
#define IDI_COLOR                       153
#define IDB_XDIRSEL                     154
#define IDI_EMITTER                     154
#define IDB_YDIRSEL                     155
#define IDI_BONE                        155
#define IDB_ZDIRSEL                     156
#define IDI_EMPTY                       156
#define IDB_ROTATEZ                     157
#define IDB_ROTATEZSEL                  159
#define IDB_PLAY                        160
#define IDI_FOLDER                      160
#define IDB_PLAYSEL                     161
#define IDI_SCENE                       161
#define IDB_STOP                        162
#define IDD_OPACITY                     163
#define IDB_STOPSEL                     163
#define IDD_VOLUME                      164
#define IDB_FFWDSEL                     164
#define IDB_PAUSE                       165
#define IDI_VOLUME                      165
#define IDD_PARTICLESIZE                166
#define IDB_PAUSESEL                    166
#define IDB_REVERSE                     167
#define IDB_REVERSESEL                  168
#define IDB_FFWD                        169
#define IDD_CAMERA                      174
#define IDI_OPENFOLD                    174
#define IDI_AGGREGATE                   175
#define IDI_TEXTUREEDIT                 176
#define IDI_NAME                        177
#define IDI_SIZE                        178
#define IDI_CAMERA                      179
#define IDD_EMITTERSIZE                 182
#define IDD_TEXTUREDIR                  183
#define IDI_ANIMSPEED                   184
#define IDI_DIRECTX                     186
#define IDI_TEXTURE                     187
#define IDI_PRIMITIVEEDIT               188
#define IDI_PRIMITIVE                   189
#define IDI_VECTOR                      190
#define IDD_ADDOBJECT                   191
#define IDI_ADDTOSCENE                  192
#define IDI_SOUND                       193
#define IDI_LINE                        194
#define IDD_CAMERADIST                  195
#define IDI_ROTATION                    195
#define IDI_FRAME                       196
#define IDD_LINEGROUP                   201
#define IDD_BLURTIME                    202
#define IDB_GAMMA                       204
#define IDC_COLORPICKER                 1000
#define IDC_SATURATIONBAR               1001
#define IDC_COLORBAR                    1002
#define IDC_PHYSICAL                    1002
#define IDC_REDBAR                      1002
#define IDC_OPACITYBAR                  1003
#define IDC_PROJECTILE                  1003
#define IDC_GREENBAR                    1003
#define IDC_SIZEBAR                     1004
#define IDC_HIDDEN                      1004
#define IDC_BLUEBAR                     1004
#define IDC_NORMAL                      1005
#define IDC_REDEDIT                     1005
#define IDC_DEVICECOMBO                 1006
#define IDC_GREENEDIT                   1006
#define IDC_COLBOX                      1006
#define IDC_SKIN                        1007
#define IDC_BLUEEDIT                    1007
#define IDC_SHADOW                      1008
#define IDC_DEVICENAME                  1008
#define IDC_DEVICEVENDOR                1009
#define IDC_DEVICEPLATFORM              1010
#define IDC_ORIGINALBAR                 1011
#define IDC_VERTICIES                   1011
#define IDC_DRIVERFILE                  1011
#define IDC_CURRENTBAR                  1012
#define IDC_POLYGONS                    1012
#define IDC_DRIVERVENDOR                1012
#define IDC_TOTALTIME                   1013
#define IDC_SUBOBJECTLIST               1013
#define IDC_DRIVERVERSION               1013
#define IDC_POLYS                       1014
#define IDC_HARDWARENAME                1014
#define IDC_SUBOBJECTS                  1015
#define IDC_HARDWAREVENDOR              1015
#define IDC_PROPERTIES                  1016
#define IDC_HARDWARECHIPSET             1016
#define IDC_USERTEXT                    1017
#define IDC_16BIT                       1017
#define IDC_24BIT                       1018
#define IDC_DRIVERNAME                  1019
#define IDC_HORFOV                      1020
#define IDC_CAMDIST                     1020
#define IDC_DISTANCE                    1020
#define IDC_PATH1                       1020
#define IDC_VERTFOV                     1021
#define IDC_PATH2                       1021
#define IDC_USERSTRING                  1021
#define IDC_RED                         1021
#define IDC_HORFOVSPIN                  1022
#define IDC_START                       1022
#define IDC_GREEN                       1022
#define IDC_VERTFOVSPIN                 1023
#define IDC_MAXPARTSPIN                 1023
#define IDC_END                         1023
#define IDC_BLUESPIN                    1023
#define IDC_FRAMESLIDER                 1023
#define IDC_RSPIN                       1023
#define IDC_REDSLIDER                   1024
#define IDC_NEARCLIP                    1024
#define IDC_RATESPIN                    1024
#define IDC_GSPIN                       1024
#define IDC_NEARCLIPSPIN                1025
#define IDC_PARTICLESSPIN               1025
#define IDC_YACCELSPIN                  1025
#define IDC_REDBOX                      1025
#define IDC_BLUE                        1025
#define IDC_GREENSLIDER                 1026
#define IDC_FARCLIP                     1026
#define IDC_MERGEABORTSPIN              1026
#define IDC_ZACCELSPIN                  1026
#define IDC_BSPIN                       1026
#define IDC_FARCLIPSPIN                 1027
#define IDC_UVTILESPIN                  1027
#define IDC_XVELSPIN                    1027
#define IDC_GREENBOX                    1027
#define IDC_OPACITY                     1027
#define IDC_BLUESLIDER                  1028
#define IDC_LENSFOV                     1028
#define IDC_OPACITYSPIN                 1028
#define IDC_UPERSECSPIN                 1028
#define IDC_YVELSPIN                    1028
#define IDC_LENSFOVSPIN                 1029
#define IDC_VPERSECSPIN                 1029
#define IDC_ZVELSPIN                    1029
#define IDC_BLUEBOX                     1029
#define IDC_GREENSPIN                   1030
#define IDC_REDSPIN                     1031
#define IDC_OUTWARDSPIN                 1033
#define IDC_INHERITSPIN                 1034
#define IDC_GREYSCALE                   1035
#define IDC_DIFFUSE                     1036
#define IDC_COMP16BIT                   1036
#define IDC_BOX                         1036
#define IDC_SPECULAR                    1037
#define IDC_COMP8BIT                    1037
#define IDC_BOTH                        1038
#define IDC_HELPBUTTON                  1038
#define IDC_BROWSE                      1039
#define IDC_SPHERE                      1039
#define IDC_TEXTURE                     1040
#define IDC_FILENAME                    1040
#define IDC_CYLINDER                    1040
#define IDC_HIERARCHIES                 1041
#define IDC_CURRENT                     1047
#define IDC_HIERARCHY                   1048
#define IDC_FRAMES                      1049
#define IDC_FRAMERATE                   1050
#define IDC_BLENDFRAMES                 1051
#define IDC_MAXPART                     1056
#define IDC_RATE                        1057
#define IDC_PARTICLES                   1058
#define IDC_YACCEL                      1058
#define IDC_LIFETIME                    1059
#define IDC_MERGEABORT                  1059
#define IDC_LIFETIMESPIN                1060
#define IDC_UVTILE                      1060
#define IDC_UPERSEC                     1061
#define IDC_ZACCEL                      1061
#define IDC_FUTURESTART                 1061
#define IDC_VPERSEC                     1062
#define IDC_XVEL                        1062
#define IDC_FUTURESTARTSPIN             1062
#define IDC_YVEL                        1063
#define IDC_ZVEL                        1064
#define IDC_OUTWARD                     1068
#define IDC_XACCEL                      1069
#define IDC_XACCELSPIN                  1070
#define IDC_INHERIT                     1071
#define IDC_RADIUS                      1071
#define IDC_RADIUSSPIN                  1072
#define IDC_CYLRADIUS                   1073
#define IDC_CYLRADIUSSPIN               1074
#define IDC_CYLHEIGHT                   1075
#define IDC_CYLHEIGHTSPIN               1076
#define IDC_USERCOMBO                   1079
#define IDC_NAME                        1080
#define IDC_FOLDERTITLE                 1088
#define IDC_DRIVETITLE                  1091
#define IDC_VERSION                     1106
#define IDC_INTENSITYSLIDER             1108
#define IDC_ENDSPIN                     1109
#define IDC_STARTSPIN                   1110
#define IDC_CAMDISTSPIN                 1111
#define IDC_DISTANCESPIN                1111
#define IDC_ATTENUATION                 1113
#define IDC_SHADER                      1117
#define IDC_MAXCHECK                    1118
#define IDC_MERGE                       1119
#define IDC_ENDCAPS                     1120
#define IDC_BOXX                        1120
#define IDC_SORTING                     1121
#define IDC_FOLDERS                     1121
#define IDC_BOXY                        1121
#define IDC_BOXZ                        1122
#define IDC_BOXXSPIN                    1123
#define IDC_BOXYSPIN                    1124
#define IDC_BOXZSPIN                    1125
#define IDC_HOLLOW                      1126
#define IDC_VOLUME                      1127
#define IDC_PSIZESPIN                   1128
#define IDC_PSIZEEDIT                   1129
#define IDC_SCALE                       1130
#define IDC_SIZEEDIT                    1130
#define IDC_SCALESPIN                   1131
#define IDC_SIZESPIN                    1131
#define IDC_RANDOMIZER                  1132
#define IDC_FOV                         1136
#define IDC_CLIPPLANES                  1137
#define IDC_DRIVES                      1137
#define IDC_LIFETIMECHECK               1138
#define IDC_BROWSE1                     1141
#define IDC_BROWSE2                     1142
#define IDC_EDITCTRL                    1152
#define IDC_OBJECT                      1159
#define IDC_BLURTIMELABEL               1160
#define IDC_SCALELABEL                  1160
#define IDC_FRAMELABEL                  1160
#define IDC_ROTLABEL                    1160
#define IDC_MAPPING                     1161
#define IDC_SUBDIVISION                 1162
#define IDC_SUBDIVISIONSPIN             1163
#define IDC_AMPLITUDE                   1164
#define IDC_AMPLITUDESPIN               1165
#define IDC_RENDERMODE                  1166
#define IDC_VELOCITY                    1167
#define IDC_VELOCITYSPIN                1168
#define IDC_TEXTUREGRID                 1169
#define IDC_ORIENTATION                 1169
#define IDC_ROTATIONBAR                 1170
#define IDC_FRAMEBAR                    1171
#define IDC_ORIENTATIONSPIN             1171
#define IDC_PFRAMESPIN                  1172
#define IDC_PFRAME                      1173
#define IDC_ROTATION                    1174
#define IDC_ROTATIONSPIN                1175
#define IDC_FRAME                       1176
#define IDC_FRAMESPIN                   1177
#define IDC_LINE                        1178
#define IDC_LINESPIN                    1179
#define IDC_LINEBAR                     1180
#define IDC_BLURTIME                    1181
#define IDC_BLURTIMESPIN                1182
#define IDC_COMPRESSQ                   1183
#define IDD_SELECTDIR                   1536
#define IDD_SCALE                       20642
#define IDD_EMITTERLINE                 20646
#define IDD_EMITTERROT                  20647
#define IDD_EMITTERFRAME                20648
#define IDD_PARTICLEROT                 20649
#define IDD_PARTICLEFRAME               20650
#define ID_OBJECT_PROPERTIES            32771
#define ID_ANIMATION_PAUSE              32772
#define ID_ANIMATION_STOP               32773
#define ID_ANIMATION_PLAY               32775
#define ID_HIERARCHY_GENERATELOD        32776
#define ID_ANIMATION_SETTINGS           32778
#define ID_CAMERA_TOP                   32779
#define ID_CAMERA_FRONT                 32780
#define ID_CAMERA_LEFT                  32781
#define ID_CAMERA_BOTTOM                32782
#define ID_CAMERA_BACK                  32783
#define ID_CAMERA_RIGHT                 32784
#define ID_CAMERA_RESET                 32785
#define ID_OBJECT_ROTATEZ               32786
#define ID_OBJECT_ROTATEX               32787
#define ID_OBJECT_ROTATEY               32788
#define ID_LIGHTING_AMBIENT             32789
#define ID_LIGHTING_SCENELIGHT          32790
#define ID_BACKGROUND_COLOR             32791
#define ID_BACKGROUND_BITMAP            32792
#define ID_BACKGROUND_OBJECT            32793
#define ID_EXPORT_LOD                   32794
#define ID_TOOLBARS_OBJECT              32798
#define ID_TOOLBARS_ANIMATION           32799
#define ID_ANIMATION_STEPFORWARD        32800
#define ID_ANIMATION_STEPBACK           32801
#define ID_CAMERA_ROTATEXONLY           32802
#define ID_CAMERA_ROTATEYONLY           32803
#define ID_CAMERA_ROTATEZONLY           32804
#define ID_OBJECT_RESET                 32805
#define ID_EMITTERS_CREATEEMITTER       32808
#define ID_EMITTERS_EDITEMITTER         32809
#define ID_EXPORT_EMITTER               32810
#define ID_EXPORT_AGGREGATE             32813
#define ID_CAMERA_ANIMATECAMERA         32814
#define ID_CAMERA_RESETONDISPLAY        32815
#define ID_LIGHTING_INCAMBIENTINTENSITY 32816
#define ID_LIGHTING_DECAMBIENTINTENSITY 32817
#define ID_LIGHTING_INCSCENELIGHTINTENSITY 32818
#define ID_LIGHTING_DECSCENELIGHTINTENSITY 32819
#define ID_OBJECT_ROTATEZBACKWARDS      32820
#define ID_OBJECT_ROTATEYBACKWARDS      32821
#define ID_LIGHTING_ROTATEY             32822
#define ID_LIGHTING_ROTATEYBACKWARDS    32823
#define ID_LIGHTING_ROTATEZ             32824
#define ID_LIGHTING_ROTATEZBACKWARDS    32825
#define ID_LOD_RECORDSCREENAREA         32831
#define ID_LOD_NEXTLEVEL                32832
#define ID_LOD_INCLUDENULLOBJECT        32833
#define ID_LOD_PREVLEVEL                32834
#define ID_LOD_AUTOSWITCHING            32835
#define ID_VIEW_PREV                    32849
#define ID_VIEW_NEXT                    32850
#define ID_CAMERA_SETTINGS              32853
#define ID_CAMERA_COPYSCREENSIZETOCLIPBOARD 32854
#define ID_FILE_TEXTUREPATH             32863
#define ID_EXPORT_PRIMITIVE             32869
#define ID_LIGHTING_KILLSCENELIGHT      32871
#define ID_ADDOBJECT                    32872
#define IDS_ADDOBJECT                   32872
#define IDS_REMOVEOBJECT                32873
#define ID_OBJECT_RESTRICTANIMS         32875
#define ID_CAMERA_SETDISTANCE           32877
#define ID_OBJECT_TOGGLEALTERNATEMATERIALS 32878
#define ID_EXPORT_SOUNDOBJECT           32881
#define ID_VIEW_WIREFRAMEMODE           32882
#define ID_BACKGROUND_FOG               32883
#define ID_EMITTERS_SCALEEMITTER        32884
#define ID_VIEW_POLYGONSORTING          32885
#define ID_CAMERA_XCAMERA               32886
#define ID_FILE_MUNGESORTONLOAD         32897
#define ID_LIGHTING_VERTEXLIGHTING      32910
#define ID_LIGHTING_MULTIPASSLIGHTING   32911
#define ID_LIGHTING_MULTITEXTURELIGHTING 32912
#define IDS_MESHPROPERTYSTRING          61204
#define IDS_MESHPROPERTIES              61205
#define IDS_HIERARCHYPROPERTYSTRING     61206
#define IDS_HIERARCHYPROPERTIES         61207
#define IDS_NOTENOUGHDETAIL             61208
#define IDS_NOTENOUGHHIERARCHIES        61209
#define IDS_POLYS                       61210
#define IDS_CAMERADIST                  61211
#define IDS_FRAMES                      61212
#define IDS_ANIMATIONPROPERTYSTRING     61213
#define IDS_ANIMATIONPROPERTIES         61214
#define IDS_EMITTERPROPERTIES           61215
#define IDS_PARTICLES                   61218
#define IDS_FRAMETIME                   61219
#define IDS_WWW                         61222

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        307
#define _APS_NEXT_COMMAND_VALUE         40365
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
