language: cpp

compiler:
  - clang
  - gcc

env:
  - 'BUILD_TYPE=Release'
  - 'BUILD_TYPE=Debug'
  
before_install:
  - sudo apt-get install -y libgtk-3-dev
  
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=TRUE ..
  
script: make -j2
