/**
 * @file
 *
 * @author Jonathan Wilson
 *
 * @brief EVA
 *
 * @copyright Thyme is free software: you can redistribute it and/or
 *            modify it under the terms of the GNU General Public License
 *            as published by the Free Software Foundation, either version
 *            2 of the License, or (at your option) any later version.
 *            A full copy of the GNU General Public License can be found in
 *            LICENSE
 */
#pragma once
#include "always.h"

enum EvaMessage
{
    EVA_MESSAGE_INVALID = -1,
    EVA_MESSAGE_LOWPOWER,
    EVA_MESSAGE_INSUFFICIENTFUNDS,
    EVA_MESSAGE_SUPERWEAPONDETECTED_OWN_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONDETECTED_OWN_NUKE,
    EVA_MESSAGE_SUPERWEAPONDETECTED_OWN_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONDETECTED_ALLY_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONDETECTED_ALLY_NUKE,
    EVA_MESSAGE_SUPERWEAPONDETECTED_ALLY_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONDETECTED_ENEMY_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONDETECTED_ENEMY_NUKE,
    EVA_MESSAGE_SUPERWEAPONDETECTED_ENEMY_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_OWN_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_OWN_NUKE,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_OWN_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ALLY_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ALLY_NUKE,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ALLY_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ENEMY_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ENEMY_NUKE,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ENEMY_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONREADY_OWN_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONREADY_OWN_NUKE,
    EVA_MESSAGE_SUPERWEAPONREADY_OWN_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONREADY_ALLY_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONREADY_ALLY_NUKE,
    EVA_MESSAGE_SUPERWEAPONREADY_ALLY_SCUDSTORM,
    EVA_MESSAGE_SUPERWEAPONREADY_ENEMY_PARTICLECANNON,
    EVA_MESSAGE_SUPERWEAPONREADY_ENEMY_NUKE,
    EVA_MESSAGE_SUPERWEAPONREADY_ENEMY_SCUDSTORM,
    EVA_MESSAGE_BUILDINGLOST,
    EVA_MESSAGE_BASEUNDERATTACK,
    EVA_MESSAGE_ALLYUNDERATTACK,
    EVA_MESSAGE_BEACONDETECTED,
    EVA_MESSAGE_ENEMYBLACKLOTUSDETECTED,
    EVA_MESSAGE_ENEMYJARMENKELLDETECTED,
    EVA_MESSAGE_ENEMYCOLONELBURTONDETECTED,
    EVA_MESSAGE_OWNBLACKLOTUSDETECTED,
    EVA_MESSAGE_OWNJARMENKELLDETECTED,
    EVA_MESSAGE_OWNCOLONELBURTONDETECTED,
    EVA_MESSAGE_UNITLOST,
    EVA_MESSAGE_GENERALLEVELUP,
    EVA_MESSAGE_VEHICLESTOLEN,
    EVA_MESSAGE_BUILDINGSTOLEN,
    EVA_MESSAGE_CASHSTOLEN,
    EVA_MESSAGE_UPGRADECOMPLETE,
    EVA_MESSAGE_BUILDINGBEINGSTOLEN,
    EVA_MESSAGE_BUILDINGSABOTAGED,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_OWN_GPS_SCRAMBLER,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ALLY_GPS_SCRAMBLER,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ENEMY_GPS_SCRAMBLER,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_OWN_SNEAK_ATTACK,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ALLY_SNEAK_ATTACK,
    EVA_MESSAGE_SUPERWEAPONLAUNCHED_ENEMY_SNEAK_ATTACK,
};

class Eva
{
public:
    void Set_Should_Play(EvaMessage message);
};

#ifdef GAME_DLL
extern Eva *&g_theEva;
#else
extern Eva *g_theEva;
#endif
