////////////////////////////////////////////////////////////////////////////////
//                               --  THYME  --                                //
////////////////////////////////////////////////////////////////////////////////
//
//  Project Name:: Thyme
//
//          File:: GAMEMESSAGE.H
//
//        Author:: OmniBlade
//
//  Contributors:: 
//
//   Description:: Message object.
//
//       License:: Thyme is free software: you can redistribute it and/or 
//                 modify it under the terms of the GNU General Public License 
//                 as published by the Free Software Foundation, either version 
//                 2 of the License, or (at your option) any later version.
//
//                 A full copy of the GNU General Public License can be found in
//                 LICENSE
//
////////////////////////////////////////////////////////////////////////////////
#ifdef _MSC_VER
#pragma once
#endif // _MSC_VER

#ifndef _GAMEMESSAGE_H_
#define _GAMEMESSAGE_H_

#include "mempoolobj.h"
#include "coord.h"

class GameMessageList;

enum ArgumentDataType
{
    ARGUMENTDATATYPE_INTEGER = 0,
    ARGUMENTDATATYPE_REAL,
    ARGUMENTDATATYPE_BOOLEAN,
    ARGUMENTDATATYPE_OBJECTID,
    ARGUMENTDATATYPE_DRAWABLEID,
    ARGUMENTDATATYPE_TEAMID,
    ARGUMENTDATATYPE_LOCATION,
    ARGUMENTDATATYPE_PIXEL,
    ARGUMENTDATATYPE_PIXELREGION,
    ARGUMENTDATATYPE_TIMESTAMP,
    ARGUMENTDATATYPE_WIDECHAR,
    ARGUMENTDATATYPE_UNKNOWN,
};

enum MessageType   //Found in some debug info, needs verifying it matches ZH
{
    MSG_INVALID = 0x0,
    MSG_FRAME_TICK = 0x1,
    MSG_RAW_MOUSE_POSITION = 0x2,
    MSG_RAW_MOUSE_LEFT_BUTTON_DOWN = 0x3,
    MSG_RAW_MOUSE_LEFT_BUTTON_UP = 0x4,
    MSG_RAW_MOUSE_LEFT_CLICK = 0x5,
    MSG_RAW_MOUSE_LEFT_DRAG = 0x6,
    MSG_RAW_MOUSE_MIDDLE_BUTTON_DOWN = 0x7,
    MSG_RAW_MOUSE_MIDDLE_BUTTON_UP = 0x8,
    MSG_RAW_MOUSE_MIDDLE_CLICK = 0x9,
    MSG_RAW_MOUSE_MIDDLE_DRAG = 0xA,
    MSG_RAW_MOUSE_RIGHT_BUTTON_DOWN = 0xB,
    MSG_RAW_MOUSE_RIGHT_BUTTON_UP = 0xC,
    MSG_RAW_MOUSE_RIGHT_CLICK = 0xD,
    MSG_RAW_MOUSE_RIGHT_DRAG = 0xE,
    MSG_RAW_MOUSE_WHEEL = 0xF,
    MSG_RAW_KEY_DOWN = 0x10,
    MSG_RAW_KEY_UP = 0x11,
    MSG_CLEAR_GAME_DATA = 0x12,
    MSG_NEW_GAME = 0x13,
    MSG_BEGIN_META_MESSAGES = 0x14,
    MSG_META_SAVE_VIEW1 = 0x15,
    MSG_META_SAVE_VIEW2 = 0x16,
    MSG_META_SAVE_VIEW3 = 0x17,
    MSG_META_SAVE_VIEW4 = 0x18,
    MSG_META_SAVE_VIEW5 = 0x19,
    MSG_META_SAVE_VIEW6 = 0x1A,
    MSG_META_SAVE_VIEW7 = 0x1B,
    MSG_META_SAVE_VIEW8 = 0x1C,
    MSG_META_VIEW_VIEW1 = 0x1D,
    MSG_META_VIEW_VIEW2 = 0x1E,
    MSG_META_VIEW_VIEW3 = 0x1F,
    MSG_META_VIEW_VIEW4 = 0x20,
    MSG_META_VIEW_VIEW5 = 0x21,
    MSG_META_VIEW_VIEW6 = 0x22,
    MSG_META_VIEW_VIEW7 = 0x23,
    MSG_META_VIEW_VIEW8 = 0x24,
    MSG_META_CREATE_TEAM0 = 0x25,
    MSG_META_CREATE_TEAM1 = 0x26,
    MSG_META_CREATE_TEAM2 = 0x27,
    MSG_META_CREATE_TEAM3 = 0x28,
    MSG_META_CREATE_TEAM4 = 0x29,
    MSG_META_CREATE_TEAM5 = 0x2A,
    MSG_META_CREATE_TEAM6 = 0x2B,
    MSG_META_CREATE_TEAM7 = 0x2C,
    MSG_META_CREATE_TEAM8 = 0x2D,
    MSG_META_CREATE_TEAM9 = 0x2E,
    MSG_META_SELECT_TEAM0 = 0x2F,
    MSG_META_SELECT_TEAM1 = 0x30,
    MSG_META_SELECT_TEAM2 = 0x31,
    MSG_META_SELECT_TEAM3 = 0x32,
    MSG_META_SELECT_TEAM4 = 0x33,
    MSG_META_SELECT_TEAM5 = 0x34,
    MSG_META_SELECT_TEAM6 = 0x35,
    MSG_META_SELECT_TEAM7 = 0x36,
    MSG_META_SELECT_TEAM8 = 0x37,
    MSG_META_SELECT_TEAM9 = 0x38,
    MSG_META_VIEW_TEAM0 = 0x39,
    MSG_META_VIEW_TEAM1 = 0x3A,
    MSG_META_VIEW_TEAM2 = 0x3B,
    MSG_META_VIEW_TEAM3 = 0x3C,
    MSG_META_VIEW_TEAM4 = 0x3D,
    MSG_META_VIEW_TEAM5 = 0x3E,
    MSG_META_VIEW_TEAM6 = 0x3F,
    MSG_META_VIEW_TEAM7 = 0x40,
    MSG_META_VIEW_TEAM8 = 0x41,
    MSG_META_VIEW_TEAM9 = 0x42,
    MSG_META_SELECT_MATCHING_UNITS = 0x43,
    MSG_META_SELECT_NEXT_UNIT = 0x44,
    MSG_META_SELECT_PREV_UNIT = 0x45,
    MSG_META_VIEW_COMMAND_CENTER = 0x46,
    MSG_META_VIEW_LAST_RADAR_EVENT = 0x47,
    MSG_META_SELECT_ALL = 0x48,
    MSG_META_SCATTER = 0x49,
    MSG_META_STOP = 0x4A,
    MSG_META_DEPLOY = 0x4B,
    MSG_META_GUARD = 0x4C,
    MSG_META_FOLLOW = 0x4D,
    MSG_META_CHAT_PLAYERS = 0x4E,
    MSG_META_CHAT_ALLIES = 0x4F,
    MSG_META_CHAT_EVERYONE = 0x50,
    MSG_META_DIPLOMACY = 0x51,
    MSG_META_OPTIONS = 0x52,
    MSG_META_DEMO_INSTANT_QUIT = 0x53,
    MSG_META_HELP = 0x54,
    MSG_META_TOGGLE_CONTROL_BAR = 0x55,
    MSG_META_TOGGLE_LETTERBOX = 0x56,
    MSG_META_TOGGLE_MESSAGE_TEXT = 0x57,
    MSG_META_BEGIN_PATH_BUILD = 0x58,
    MSG_META_END_PATH_BUILD = 0x59,
    MSG_META_BEGIN_ESCORT = 0x5A,
    MSG_META_END_ESCORT = 0x5B,
    MSG_META_BEGIN_FORCEATTACK = 0x5C,
    MSG_META_END_FORCEATTACK = 0x5D,
    MSG_META_BEGIN_ATTACKMOVE = 0x5E,
    MSG_META_END_ATTACKMOVE = 0x5F,
    MSG_META_TAKE_SCREENSHOT = 0x60,
    MSG_META_ALL_CHEER = 0x61,
    MSG_META_PLAY_CAMEO_MOVIE = 0x62,
    MSG_META_TOGGLE_ZOOM_LOCK = 0x63,
    MSG_META_TOGGLE_SPECIAL_POWER_DELAYS = 0x64,
    MSG_META_DEMO_BATTLE_CRY = 0x65,
    MSG_META_DEMO_SWITCH_TEAMS = 0x66,
    MSG_META_DEMO_SWITCH_TEAMS_BETWEEN_CHINA_USA = 0x67,
    MSG_META_DEMO_TOGGLE_DEBUG_STATS = 0x68,
    MSG_META_DEMO_TOGGLE_AUDIODEBUG = 0x69,
    MSG_META_DEMO_TOGGLE_PARTICLEDEBUG = 0x6A,
    MSG_META_DEMO_LOD_DECREASE = 0x6B,
    MSG_META_DEMO_LOD_INCREASE = 0x6C,
    MSG_META_DEMO_TOGGLE_SHADOW_VOLUMES = 0x6D,
    MSG_META_DEMO_TOGGLE_FOGOFWAR = 0x6E,
    MSG_META_DEMO_KILL_SELECTION = 0x6F,
    MSG_META_DEMO_HURT_SELECTION = 0x70,
    MSG_META_DEMO_DEBUG_SELECTION = 0x71,
    MSG_META_DEMO_LOCK_CAMERA_TO_SELECTION = 0x72,
    MSG_META_DEMO_TOGGLE_SOUND = 0x73,
    MSG_META_DEMO_TOGGLE_TRACKMARKS = 0x74,
    MSG_META_DEMO_TOGGLE_WATERPLANE = 0x75,
    MSG_META_DEMO_TIME_OF_DAY = 0x76,
    MSG_META_DEMO_TOGGLE_MUSIC = 0x77,
    MSG_META_DEMO_MUSIC_NEXT_TRACK = 0x78,
    MSG_META_DEMO_MUSIC_PREV_TRACK = 0x79,
    MSG_META_DEMO_NEXT_OBJECTIVE_MOVIE = 0x7A,
    MSG_META_DEMO_PLAY_OBJECTIVE_MOVIE1 = 0x7B,
    MSG_META_DEMO_PLAY_OBJECTIVE_MOVIE2 = 0x7C,
    MSG_META_DEMO_PLAY_OBJECTIVE_MOVIE3 = 0x7D,
    MSG_META_DEMO_PLAY_OBJECTIVE_MOVIE4 = 0x7E,
    MSG_META_DEMO_PLAY_OBJECTIVE_MOVIE5 = 0x7F,
    MSG_META_DEMO_PLAY_OBJECTIVE_MOVIE6 = 0x80,
    MSG_META_DEMO_BEGIN_ADJUST_PITCH = 0x81,
    MSG_META_DEMO_END_ADJUST_PITCH = 0x82,
    MSG_META_DEMO_BEGIN_ADJUST_FOV = 0x83,
    MSG_META_DEMO_END_ADJUST_FOV = 0x84,
    MSG_META_DEMO_LOCK_CAMERA_TO_PLANES = 0x85,
    MSG_META_DEMO_REMOVE_PREREQ = 0x86,
    MSG_META_DEMO_INSTANT_BUILD = 0x87,
    MSG_META_DEMO_FREE_BUILD = 0x88,
    MSG_META_DEMO_RUNSCRIPT1 = 0x89,
    MSG_META_DEMO_RUNSCRIPT2 = 0x8A,
    MSG_META_DEMO_RUNSCRIPT3 = 0x8B,
    MSG_META_DEMO_RUNSCRIPT4 = 0x8C,
    MSG_META_DEMO_RUNSCRIPT5 = 0x8D,
    MSG_META_DEMO_RUNSCRIPT6 = 0x8E,
    MSG_META_DEMO_RUNSCRIPT7 = 0x8F,
    MSG_META_DEMO_RUNSCRIPT8 = 0x90,
    MSG_META_DEMO_RUNSCRIPT9 = 0x91,
    MSG_META_DEMO_ENSHROUD = 0x92,
    MSG_META_DEMO_DESHROUD = 0x93,
    MSG_META_DEBUG_SHOW_EXTENTS = 0x94,
    MSG_META_DEBUG_SHOW_HEALTH = 0x95,
    MSG_META_DEBUG_GIVE_VETERANCY = 0x96,
    MSG_META_DEBUG_TAKE_VETERANCY = 0x97,
    MSG_META_DEMO_TOGGLE_AI_DEBUG = 0x98,
    MSG_META_DEMO_TOGGLE_AVI = 0x99,
    MSG_META_DEMO_TOGGLE_BW_VIEW = 0x9A,
    MSG_META_DEMO_TOGGLE_RED_VIEW = 0x9B,
    MSG_META_DEMO_TOGGLE_GREEN_VIEW = 0x9C,
    MSG_META_DEMO_TOGGLE_MOTION_BLUR_ZOOM = 0x9D,
    MSG_META_DEMO_TOGGLE_MILITARY_SUBTITLES = 0x9E,
    MSG_META_DEMO_ADD_CASH = 0x9F,
    MSG_META_DEBUG_CYCLE_EXTENT_TYPE = 0xA0,
    MSG_META_DEBUG_INCREASE_EXTENT_MAJOR = 0xA1,
    MSG_META_DEBUG_INCREASE_EXTENT_MAJOR_BIG = 0xA2,
    MSG_META_DEBUG_DECREASE_EXTENT_MAJOR = 0xA3,
    MSG_META_DEBUG_DECREASE_EXTENT_MAJOR_BIG = 0xA4,
    MSG_META_DEBUG_INCREASE_EXTENT_MINOR = 0xA5,
    MSG_META_DEBUG_INCREASE_EXTENT_MINOR_BIG = 0xA6,
    MSG_META_DEBUG_DECREASE_EXTENT_MINOR = 0xA7,
    MSG_META_DEBUG_DECREASE_EXTENT_MINOR_BIG = 0xA8,
    MSG_META_DEBUG_INCREASE_EXTENT_HEIGHT = 0xA9,
    MSG_META_DEBUG_INCREASE_EXTENT_HEIGHT_BIG = 0xAA,
    MSG_META_DEBUG_DECREASE_EXTENT_HEIGHT = 0xAB,
    MSG_META_DEBUG_DECREASE_EXTENT_HEIGHT_BIG = 0xAC,
    MSG_META_DEBUG_VTUNE_ON = 0xAD,
    MSG_META_DEBUG_VTUNE_OFF = 0xAE,
    MSG_NO_DRAW = 0xAF,
    MSG_END_META_MESSAGES = 0xB0,
    MSG_MOUSEOVER_DRAWABLE_HINT = 0xB1,
    MSG_MOUSEOVER_LOCATION_HINT = 0xB2,
    MSG_VALID_GUICOMMAND_HINT = 0xB3,
    MSG_INVALID_GUICOMMAND_HINT = 0xB4,
    MSG_AREA_SELECTION_HINT = 0xB5,
    MSG_DO_ATTACK_GROUND_OBJECT_HINT = 0xB6,
    MSG_GET_REPAIRED_HINT = 0xB7,
    MSG_GET_HEALED_HINT = 0xB8,
    MSG_DO_REPAIR_HINT = 0xB9,
    MSG_RESUME_CONSTRUCTION_HINT = 0xBA,
    MSG_ENTER_HINT = 0xBB,
    MSG_TRANSFER_SUPPLIES_HINT = 0xBC,
    MSG_DO_MOVETO_HINT = 0xBD,
    MSG_DO_ATTACKMOVETO_HINT = 0xBE,
    MSG_CONVERT_TO_CARBOMB_HINT = 0xBF,
    MSG_CAPTUREBUILDING_HACK_HINT = 0xC0,
    MSG_DISABLEVEHICLE_HACK_HINT = 0xC1,
    MSG_STEALCASH_HACK_HINT = 0xC2,
    MSG_DISABLEBUILDING_HACK_HINT = 0xC3,
    MSG_SNIPE_VEHICLE_HINT = 0xC4,
    MSG_BEGIN_NETWORK_MESSAGES = 0xC5,
    MSG_DRAWABLE_PICKED = 0xC6,
    MSG_CREATE_SELECTED_GROUP = 0xC7,
    MSG_DESTROY_SELECTED_GROUP = 0xC8,
    MSG_SELECTED_GROUP_COMMAND = 0xC9,
    MSG_DO_ATTACKSQUAD = 0xCA,
    MSG_DO_WEAPON = 0xCB,
    MSG_DO_WEAPON_AT_LOCATION = 0xCC,
    MSG_DO_WEAPON_AT_OBJECT = 0xCD,
    MSG_DO_SPECIAL_POWER = 0xCE,
    MSG_DO_SPECIAL_POWER_AT_LOCATION = 0xCF,
    MSG_DO_SPECIAL_POWER_AT_OBJECT = 0xD0,
    MSG_SET_RALLY_POINT = 0xD1,
    MSG_PICK_SPECIALIZED_SCIENCE = 0xD2,
    MSG_QUEUE_UPGRADE = 0xD3,
    MSG_CANCEL_UPGRADE = 0xD4,
    MSG_QUEUE_UNIT_CREATE = 0xD5,
    MSG_CANCEL_UNIT_CREATE = 0xD6,
    MSG_DOZER_CONSTRUCT = 0xD7,
    MSG_DOZER_CONSTRUCT_LINE = 0xD8,
    MSG_DOZER_CANCEL_CONSTRUCT = 0xD9,
    MSG_EXIT = 0xDA,
    MSG_EVACUATE = 0xDB,
    MSG_AREA_SELECTION = 0xDC,
    MSG_DO_ATTACK_GROUND_OBJECT = 0xDD,
    MSG_GET_REPAIRED = 0xDE,
    MSG_GET_HEALED = 0xDF,
    MSG_DO_REPAIR = 0xE0,
    MSG_RESUME_CONSTRUCTION = 0xE1,
    MSG_ENTER = 0xE2,
    MSG_DOCK = 0xE3,
    MSG_DO_MOVETO = 0xE4,
    MSG_DO_ATTACKMOVETO = 0xE5,
    MSG_DO_GUARD = 0xE6,
    MSG_DO_STOP = 0xE7,
    MSG_DO_SCATTER = 0xE8,
    MSG_INTERNET_HACK = 0xE9,
    MSG_CONVERT_TO_CARBOMB = 0xEA,
    MSG_CAPTUREBUILDING_HACK = 0xEB,
    MSG_DISABLEVEHICLE_HACK = 0xEC,
    MSG_STEALCASH_HACK = 0xED,
    MSG_DISABLEBUILDING_HACK = 0xEE,
    MSG_SNIPE_VEHICLE = 0xEF,
    MSG_END_NETWORK_MESSAGES = 0xF0,
    MSG_TIMESTAMP = 0xF1,
    MSG_OBJECT_CREATED = 0xF2,
    MSG_OBJECT_DESTROYED = 0xF3,
    MSG_OBJECT_POSITION = 0xF4,
    MSG_OBJECT_ORIENTATION = 0xF5,
    MSG_OBJECT_JOINED_TEAM = 0xF6,
    MSG_COUNT = 0xF7,
};

union ArgumentType
{
    int integer;
    float real;
    bool boolean;
    unsigned int objectID;
    unsigned int drawableID;
    unsigned int teamID;
    Coord3D position;
    ICoord2D pixel;
    IRegion2D region;
    unsigned int timestamp;
    wchar_t widechar;
};

class GameMessageArgument : public MemoryPoolObject
{
    IMPLEMENT_POOL(GameMessageArgument);

public:
    GameMessageArgument *m_next;
    ArgumentType m_data;
    ArgumentDataType m_type;
};

class GameMessage : public MemoryPoolObject
{
    IMPLEMENT_POOL(GameMessage);

    friend class GameMessageList;

public:
    GameMessage(MessageType type);
    virtual ~GameMessage();

    GameMessageArgument *Allocate_Arg();
    ArgumentType *Get_Argument(int arg);
    ArgumentDataType Get_Argument_Type(int arg);

    void Append_Int_Arg(int arg);
    void Append_Real_Arg(float arg);
    void Append_Bool_Arg(bool arg);
    void Append_ObjectID_Arg(unsigned int arg);
    void Append_DrawableID_Arg(unsigned int arg);
    void Append_TeamID_Arg(unsigned int arg);
    void Append_Location_Arg(Coord3D const &arg);
    void Append_Pixel_Arg(ICoord2D const &arg);
    void Append_Region_Arg(IRegion2D const &arg);
    void Append_Time_Stamp_Arg(unsigned int arg);
    void Append_Wide_Char_Arg(wchar_t arg);

private:
    GameMessage *m_next;
    GameMessage *m_prev;
    GameMessageList *m_list;
    MessageType m_type;
    int m_playerIndex;
    int8_t m_argCount;
    // 3 bytes padding
    GameMessageArgument *m_argList;
    GameMessageArgument *m_argTail;
};

#endif
