////////////////////////////////////////////////////////////////////////////////
//                               --  THYME  --                                //
////////////////////////////////////////////////////////////////////////////////
//
//  Project Name:: Thyme
//
//          File:: GLOBALDATA.CPP
//
//        Author:: OmniBlade
//
//  Contributors:: 
//
//   Description:: Class for handling various global variables
//
//       License:: Thyme is free software: you can redistribute it and/or 
//                 modify it under the terms of the GNU General Public License 
//                 as published by the Free Software Foundation, either version 
//                 2 of the License, or (at your option) any later version.
//
//                 A full copy of the GNU General Public License can be found in
//                 LICENSE
//
////////////////////////////////////////////////////////////////////////////////
#include "globaldata.h"

// List of keys handled in the ini
// Class contains some variables that don't appear to be user
// controlled.
#if 0
FieldParse GlobalData::FieldParseTable[337] =
{
    { "Windowed", &INI::parseBool, nullptr, 32 },//
    { "XResolution", &INI::parseInt, nullptr, 36 },//
    { "YResolution", &INI::parseInt, nullptr, 40 },//
    { "MapName", &INI::parseAsciiString, nullptr, 8 },//
    { "MoveHintName", &INI::parseAsciiString, nullptr, 12 },//
    { "UseTrees", &INI::parseBool, nullptr, 16 },//
    { "UseFPSLimit", &INI::parseBool, nullptr, 20 },//
    { "DumpAssetUsage", &INI::parseBool, nullptr, 21 },//
    { "FramesPerSecondLimit", &INI::parseInt, nullptr, 24 },//
    { "ChipsetType", &INI::parseInt, nullptr, 28 },//
    { "MaxShellScreens", &INI::parseInt, nullptr, 44 },//
    { "UseCloudMap", &INI::parseBool, nullptr, 48 },//
    { "UseLightMap", &INI::parseBool, nullptr, 56 },//
    { "BilinearTerrainTex", &INI::parseBool, nullptr, 57 },//
    { "TrilinearTerrainTex", &INI::parseBool, nullptr, 58 },//
    { "MultiPassTerrain", &INI::parseBool, nullptr, 59 },//
    { "AdjustCliffTextures", &INI::parseBool, nullptr, 60 },//
    { "Use3WayTerrainBlends", &INI::parseInt, nullptr, 52 },//
    { "StretchTerrain", &INI::parseBool, nullptr, 61 },//
    { "UseHalfHeightMap", &INI::parseBool, nullptr, 62 },//
    { "DrawEntireTerrain", &INI::parseBool, nullptr, 63 },//
    { "TerrainLOD", &INI::parseIndexList, &TerrainLODNames, 64 },//
    { "TerrainLODTargetTimeMS", &INI::parseInt, nullptr, 72 },//
    { "RightMouseAlwaysScrolls", &INI::parseBool, nullptr, 79 },//
    { "UseWaterPlane", &INI::parseBool, nullptr, 80 },//
    { "UseCloudPlane", &INI::parseBool, nullptr, 81 },//
    { "DownwindAngle", &INI::parseReal, nullptr, 348 },//
    { "UseShadowVolumes", &INI::parseBool, nullptr, 82 },//
    { "UseShadowDecals", &INI::parseBool, nullptr, 83 },//
    { "TextureReductionFactor", &INI::parseInt, nullptr, 84 },//
    { "UseBehindBuildingMarker", &INI::parseBool, nullptr, 88 },//
    { "WaterPositionX", &INI::parseReal, nullptr, 92 },//
    { "WaterPositionY", &INI::parseReal, nullptr, 96 },//
    { "WaterPositionZ", &INI::parseReal, nullptr, 100 },//
    { "WaterExtentX", &INI::parseReal, nullptr, 104 },//
    { "WaterExtentY", &INI::parseReal, nullptr, 108 },//
    { "WaterType", &INI::parseInt, nullptr, 112 },//
    { "FeatherWater", &INI::parseInt, nullptr, 120 },//
    { "ShowSoftWaterEdge", &INI::parseBool, nullptr, 116 },//
    { "VertexWaterAvailableMaps1", &INI::parseAsciiString, nullptr, 124 },//
    { "VertexWaterHeightClampLow1", &INI::parseReal, nullptr, 140 },//
    { "VertexWaterHeightClampHi1", &INI::parseReal, nullptr, 156 },//
    { "VertexWaterAngle1", &INI::parseAngleReal, nullptr, 172 },//
    { "VertexWaterXPosition1", &INI::parseReal, nullptr, 188 },//
    { "VertexWaterYPosition1", &INI::parseReal, nullptr, 204 },//
    { "VertexWaterZPosition1", &INI::parseReal, nullptr, 220 },//
    { "VertexWaterXGridCells1", &INI::parseInt, nullptr, 236 },
    { "VertexWaterYGridCells1", &INI::parseInt, nullptr, 252 },
    { "VertexWaterGridSize1", &INI::parseReal, nullptr, 268 },//
    { "VertexWaterAttenuationA1", &INI::parseReal, nullptr, 284 },
    { "VertexWaterAttenuationB1", &INI::parseReal, nullptr, 300 },
    { "VertexWaterAttenuationC1", &INI::parseReal, nullptr, 316 },
    { "VertexWaterAttenuationRange1", &INI::parseReal, nullptr, 332 },
    { "VertexWaterAvailableMaps2", &INI::parseAsciiString, nullptr, 128 },
    { "VertexWaterHeightClampLow2", &INI::parseReal, nullptr, 144 },
    { "VertexWaterHeightClampHi2", &INI::parseReal, nullptr, 160 },
    { "VertexWaterAngle2", &INI::parseAngleReal, nullptr, 176 },
    { "VertexWaterXPosition2", &INI::parseReal, nullptr, 192 },
    { "VertexWaterYPosition2", &INI::parseReal, nullptr, 208 },
    { "VertexWaterZPosition2", &INI::parseReal, nullptr, 224 },
    { "VertexWaterXGridCells2", &INI::parseInt, nullptr, 240 },
    { "VertexWaterYGridCells2", &INI::parseInt, nullptr, 256 },
    { "VertexWaterGridSize2", &INI::parseReal, nullptr, 272 },
    { "VertexWaterAttenuationA2", &INI::parseReal, nullptr, 288 },
    { "VertexWaterAttenuationB2", &INI::parseReal, nullptr, 304 },
    { "VertexWaterAttenuationC2", &INI::parseReal, nullptr, 320 },
    { "VertexWaterAttenuationRange2", &INI::parseReal, nullptr, 336 },
    { "VertexWaterAvailableMaps3", &INI::parseAsciiString, nullptr, 132 },
    { "VertexWaterHeightClampLow3", &INI::parseReal, nullptr, 148 },
    { "VertexWaterHeightClampHi3", &INI::parseReal, nullptr, 164 },
    { "VertexWaterAngle3", &INI::parseAngleReal, nullptr, 180 },
    { "VertexWaterXPosition3", &INI::parseReal, nullptr, 196 },
    { "VertexWaterYPosition3", &INI::parseReal, nullptr, 212 },
    { "VertexWaterZPosition3", &INI::parseReal, nullptr, 228 },
    { "VertexWaterXGridCells3", &INI::parseInt, nullptr, 244 },
    { "VertexWaterYGridCells3", &INI::parseInt, nullptr, 260 },
    { "VertexWaterGridSize3", &INI::parseReal, nullptr, 276 },
    { "VertexWaterAttenuationA3", &INI::parseReal, nullptr, 292 },
    { "VertexWaterAttenuationB3", &INI::parseReal, nullptr, 308 },
    { "VertexWaterAttenuationC3", &INI::parseReal, nullptr, 324 },
    { "VertexWaterAttenuationRange3", &INI::parseReal, nullptr, 340 },
    { "VertexWaterAvailableMaps4", &INI::parseAsciiString, nullptr, 136 },
    { "VertexWaterHeightClampLow4", &INI::parseReal, nullptr, 152 },
    { "VertexWaterHeightClampHi4", &INI::parseReal, nullptr, 168 },
    { "VertexWaterAngle4", &INI::parseAngleReal, nullptr, 184 },
    { "VertexWaterXPosition4", &INI::parseReal, nullptr, 200 },
    { "VertexWaterYPosition4", &INI::parseReal, nullptr, 216 },
    { "VertexWaterZPosition4", &INI::parseReal, nullptr, 232 },
    { "VertexWaterXGridCells4", &INI::parseInt, nullptr, 248 },
    { "VertexWaterYGridCells4", &INI::parseInt, nullptr, 264 },
    { "VertexWaterGridSize4", &INI::parseReal, nullptr, 280 },
    { "VertexWaterAttenuationA4", &INI::parseReal, nullptr, 296 },
    { "VertexWaterAttenuationB4", &INI::parseReal, nullptr, 312 },
    { "VertexWaterAttenuationC4", &INI::parseReal, nullptr, 328 },
    { "VertexWaterAttenuationRange4", &INI::parseReal, nullptr, 344 },//
    { "SkyBoxPositionZ", &INI::parseReal, nullptr, 352 },//
    { "SkyBoxScale", &INI::parseReal, nullptr, 360 },//
    { "DrawSkyBox", &INI::parseBool, nullptr, 356 },//
    { "CameraPitch", &INI::parseReal, nullptr, 364 },//
    { "CameraYaw", &INI::parseReal, nullptr, 368 },//
    { "CameraHeight", &INI::parseReal, nullptr, 372 },//
    { "MaxCameraHeight", &INI::parseReal, nullptr, 376 },//
    { "MinCameraHeight", &INI::parseReal, nullptr, 380 },//
    { "TerrainHeightAtEdgeOfMap", &INI::parseReal, nullptr, 384 },//
    { "UnitDamagedThreshold", &INI::parseReal, nullptr, 388 },//
    { "UnitReallyDamagedThreshold", &INI::parseReal, nullptr, 392 },//
    { "GroundStiffness", &INI::parseReal, nullptr, 396 },//
    { "StructureStiffness", &INI::parseReal, nullptr, 400 },//
    { "Gravity", &INI::parseAccelerationReal, nullptr, 404 },//
    { "StealthFriendlyOpacity", &INI::parsePercentToReal, nullptr, 408 },//
    { "DefaultOcclusionDelay", &INI::parseDurationUnsignedInt, nullptr, 412 },//
    { "PartitionCellSize", &INI::parseReal, nullptr, 420 },//
    { "AmmoPipScaleFactor", &INI::parseReal, nullptr, 464 },//
    { "ContainerPipScaleFactor", &INI::parseReal, nullptr, 468 },//
    { "AmmoPipWorldOffset", &INI::parseCoord3D, nullptr, 424 },//
    { "ContainerPipWorldOffset", &INI::parseCoord3D, nullptr, 436 },//
    { "AmmoPipScreenOffset", &INI::parseCoord2D, nullptr, 448 },//
    { "ContainerPipScreenOffset", &INI::parseCoord2D, nullptr, 456 },//
    { "HistoricDamageLimit", &INI::parseDurationUnsignedInt, nullptr, 472 },//
    { "MaxTerrainTracks", &INI::parseInt, nullptr, 476 },//
    { "TimeOfDay", &INI::parseIndexList, &TimeOfDayNames, 516 },//
    { "Weather", &INI::parseIndexList, &WeatherNames, 520 },//
    { "MakeTrackMarks", &INI::parseBool, nullptr, 524 },//
    { "HideGarrisonFlags", &INI::parseBool, nullptr, 525 },//
    { "ForceModelsToFollowTimeOfDay", &INI::parseBool, nullptr, 526 },//
    { "ForceModelsToFollowWeather", &INI::parseBool, nullptr, 527 },//
    { "LevelGainAnimationName", &INI::parseAsciiString, nullptr, 492 },//
    { "LevelGainAnimationTime", &INI::parseReal, nullptr, 496 },//
    { "LevelGainAnimationZRise", &INI::parseReal, nullptr, 500 },//
    { "GetHealedAnimationName", &INI::parseAsciiString, nullptr, 504 },//
    { "GetHealedAnimationTime", &INI::parseReal, nullptr, 508 },//
    { "GetHealedAnimationZRise", &INI::parseReal, nullptr, 512 },//
    { "TerrainLightingMorningAmbient", &INI::parseRGBColor, nullptr, 636 },
    { "TerrainLightingMorningDiffuse", &INI::parseRGBColor, nullptr, 648 },
    { "TerrainLightingMorningLightPos", &INI::parseCoord3D, nullptr, 660 },
    { "TerrainLightingAfternoonAmbient", &INI::parseRGBColor, nullptr, 744 },
    { "TerrainLightingAfternoonDiffuse", &INI::parseRGBColor, nullptr, 756 },
    { "TerrainLightingAfternoonLightPos", &INI::parseCoord3D, nullptr, 768 },
    { "TerrainLightingEveningAmbient", &INI::parseRGBColor, nullptr, 852 },
    { "TerrainLightingEveningDiffuse", &INI::parseRGBColor, nullptr, 864 },
    { "TerrainLightingEveningLightPos", &INI::parseCoord3D, nullptr, 876 },
    { "TerrainLightingNightAmbient", &INI::parseRGBColor, nullptr, 960 },
    { "TerrainLightingNightDiffuse", &INI::parseRGBColor, nullptr, 972 },
    { "TerrainLightingNightLightPos", &INI::parseCoord3D, nullptr, 984 },
    { "TerrainObjectsLightingMorningAmbient", &INI::parseRGBColor, nullptr, 1176 },
    { "TerrainObjectsLightingMorningDiffuse", &INI::parseRGBColor, nullptr, 1188 },
    { "TerrainObjectsLightingMorningLightPos", &INI::parseCoord3D, nullptr, 1200 },
    { "TerrainObjectsLightingAfternoonAmbient", &INI::parseRGBColor, nullptr, 1284 },
    { "TerrainObjectsLightingAfternoonDiffuse", &INI::parseRGBColor, nullptr, 1296 },
    { "TerrainObjectsLightingAfternoonLightPos", &INI::parseCoord3D, nullptr, 1308 },
    { "TerrainObjectsLightingEveningAmbient", &INI::parseRGBColor, nullptr, 1392 },
    { "TerrainObjectsLightingEveningDiffuse", &INI::parseRGBColor, nullptr, 1404 },
    { "TerrainObjectsLightingEveningLightPos", &INI::parseCoord3D, nullptr, 1416 },
    { "TerrainObjectsLightingNightAmbient", &INI::parseRGBColor, nullptr, 1500 },
    { "TerrainObjectsLightingNightDiffuse", &INI::parseRGBColor, nullptr, 1512 },
    { "TerrainObjectsLightingNightLightPos", &INI::parseCoord3D, nullptr, 1524 },
    { "TerrainLightingMorningAmbient2", &INI::parseRGBColor, nullptr, 672 },
    { "TerrainLightingMorningDiffuse2", &INI::parseRGBColor, nullptr, 684 },
    { "TerrainLightingMorningLightPos2", &INI::parseCoord3D, nullptr, 696 },
    { "TerrainLightingAfternoonAmbient2", &INI::parseRGBColor, nullptr, 780 },
    { "TerrainLightingAfternoonDiffuse2", &INI::parseRGBColor, nullptr, 792 },
    { "TerrainLightingAfternoonLightPos2", &INI::parseCoord3D, nullptr, 804 },
    { "TerrainLightingEveningAmbient2", &INI::parseRGBColor, nullptr, 888 },
    { "TerrainLightingEveningDiffuse2", &INI::parseRGBColor, nullptr, 900 },
    { "TerrainLightingEveningLightPos2", &INI::parseCoord3D, nullptr, 912 },
    { "TerrainLightingNightAmbient2", &INI::parseRGBColor, nullptr, 996 },
    { "TerrainLightingNightDiffuse2", &INI::parseRGBColor, nullptr, 1008 },
    { "TerrainLightingNightLightPos2", &INI::parseCoord3D, nullptr, 1020 },
    { "TerrainObjectsLightingMorningAmbient2", &INI::parseRGBColor, nullptr, 1212 },
    { "TerrainObjectsLightingMorningDiffuse2", &INI::parseRGBColor, nullptr, 1224 },
    { "TerrainObjectsLightingMorningLightPos2", &INI::parseCoord3D, nullptr, 1236 },
    { "TerrainObjectsLightingAfternoonAmbient2", &INI::parseRGBColor, nullptr, 1320 },
    { "TerrainObjectsLightingAfternoonDiffuse2", &INI::parseRGBColor, nullptr, 1332 },
    { "TerrainObjectsLightingAfternoonLightPos2", &INI::parseCoord3D, nullptr, 1344 },
    { "TerrainObjectsLightingEveningAmbient2", &INI::parseRGBColor, nullptr, 1428 },
    { "TerrainObjectsLightingEveningDiffuse2", &INI::parseRGBColor, nullptr, 1440 },
    { "TerrainObjectsLightingEveningLightPos2", &INI::parseCoord3D, nullptr, 1452 },
    { "TerrainObjectsLightingNightAmbient2", &INI::parseRGBColor, nullptr, 1536 },
    { "TerrainObjectsLightingNightDiffuse2", &INI::parseRGBColor, nullptr, 1548 },
    { "TerrainObjectsLightingNightLightPos2", &INI::parseCoord3D, nullptr, 1560 },
    { "TerrainLightingMorningAmbient3", &INI::parseRGBColor, nullptr, 708 },
    { "TerrainLightingMorningDiffuse3", &INI::parseRGBColor, nullptr, 720 },
    { "TerrainLightingMorningLightPos3", &INI::parseCoord3D, nullptr, 732 },
    { "TerrainLightingAfternoonAmbient3", &INI::parseRGBColor, nullptr, 816 },
    { "TerrainLightingAfternoonDiffuse3", &INI::parseRGBColor, nullptr, 828 },
    { "TerrainLightingAfternoonLightPos3", &INI::parseCoord3D, nullptr, 840 },
    { "TerrainLightingEveningAmbient3", &INI::parseRGBColor, nullptr, 924 },
    { "TerrainLightingEveningDiffuse3", &INI::parseRGBColor, nullptr, 936 },
    { "TerrainLightingEveningLightPos3", &INI::parseCoord3D, nullptr, 948 },
    { "TerrainLightingNightAmbient3", &INI::parseRGBColor, nullptr, 1032 },
    { "TerrainLightingNightDiffuse3", &INI::parseRGBColor, nullptr, 1044 },
    { "TerrainLightingNightLightPos3", &INI::parseCoord3D, nullptr, 1056 },
    { "TerrainObjectsLightingMorningAmbient3", &INI::parseRGBColor, nullptr, 1248 },
    { "TerrainObjectsLightingMorningDiffuse3", &INI::parseRGBColor, nullptr, 1260 },
    { "TerrainObjectsLightingMorningLightPos3", &INI::parseCoord3D, nullptr, 1272 },
    { "TerrainObjectsLightingAfternoonAmbient3", &INI::parseRGBColor, nullptr, 1356 },
    { "TerrainObjectsLightingAfternoonDiffuse3", &INI::parseRGBColor, nullptr, 1368 },
    { "TerrainObjectsLightingAfternoonLightPos3", &INI::parseCoord3D, nullptr, 1380 },
    { "TerrainObjectsLightingEveningAmbient3", &INI::parseRGBColor, nullptr, 1464 },
    { "TerrainObjectsLightingEveningDiffuse3", &INI::parseRGBColor, nullptr, 1476 },
    { "TerrainObjectsLightingEveningLightPos3", &INI::parseCoord3D, nullptr, 1488 },
    { "TerrainObjectsLightingNightAmbient3", &INI::parseRGBColor, nullptr, 1572 },
    { "TerrainObjectsLightingNightDiffuse3", &INI::parseRGBColor, nullptr, 1584 },
    { "TerrainObjectsLightingNightLightPos3", &INI::parseCoord3D, nullptr, 1596 },
    { "NumberGlobalLights", &INI::parseInt, nullptr, 1784 },//
    { "InfantryLightMorningScale", &INI::parseReal, nullptr, 1720 },//
    { "InfantryLightAfternoonScale", &INI::parseReal, nullptr, 1724 },//
    { "InfantryLightEveningScale", &INI::parseReal, nullptr, 1728 },//
    { "InfantryLightNightScale", &INI::parseReal, nullptr, 1732 },//
    { "MaxTranslucentObjects", &INI::parseInt, nullptr, 1764 },//
    { "OccludedColorLuminanceScale", &INI::parseReal, nullptr, 1780 },//
    { "MaxRoadSegments", &INI::parseInt, nullptr, 1788 },//
    { "MaxRoadVertex", &INI::parseInt, nullptr, 1792 },//
    { "MaxRoadIndex", &INI::parseInt, nullptr, 1796 },//
    { "MaxRoadTypes", &INI::parseInt, nullptr, 1800 },//
    { "ValuePerSupplyBox", &INI::parseInt, nullptr, 1952 },//
    { "AudioOn", &INI::parseBool, nullptr, 1804 },//
    { "MusicOn", &INI::parseBool, nullptr, 1805 },//
    { "SoundsOn", &INI::parseBool, nullptr, 1806 },//
    { "Sounds3DOn", &INI::parseBool, nullptr, 1807 },//
    { "SpeechOn", &INI::parseBool, nullptr, 1808 },//
    { "VideoOn", &INI::parseBool, nullptr, 1809 },//
    { "DisableCameraMovements", &INI::parseBool, nullptr, 1810 },//
    { "DebugAI", &INI::parseBool, nullptr, 1820 },//
    { "DebugAIObstacles", &INI::parseBool, nullptr, 1825 },//
    { "ShowClientPhysics", &INI::parseBool, nullptr, 1812 },//
    { "ShowTerrainNormals", &INI::parseBool, nullptr, 1813 },//
    { "ShowObjectHealth", &INI::parseBool, nullptr, 1826 },//
    { "ParticleScale", &INI::parseReal, nullptr, 1840 },//
    { "AutoFireParticleSmallPrefix", &INI::parseAsciiString, nullptr, 1844 },//
    { "AutoFireParticleSmallSystem", &INI::parseAsciiString, nullptr, 1848 },//
    { "AutoFireParticleSmallMax", &INI::parseInt, nullptr, 1852 },//
    { "AutoFireParticleMediumPrefix", &INI::parseAsciiString, nullptr, 1856 },//
    { "AutoFireParticleMediumSystem", &INI::parseAsciiString, nullptr, 1860 },//
    { "AutoFireParticleMediumMax", &INI::parseInt, nullptr, 1864 },//
    { "AutoFireParticleLargePrefix", &INI::parseAsciiString, nullptr, 1868 },//
    { "AutoFireParticleLargeSystem", &INI::parseAsciiString, nullptr, 1872 },//
    { "AutoFireParticleLargeMax", &INI::parseInt, nullptr, 1876 },//
    { "AutoSmokeParticleSmallPrefix", &INI::parseAsciiString, nullptr, 1880 },//
    { "AutoSmokeParticleSmallSystem", &INI::parseAsciiString, nullptr, 1884 },//
    { "AutoSmokeParticleSmallMax", &INI::parseInt, nullptr, 1888 },//
    { "AutoSmokeParticleMediumPrefix", &INI::parseAsciiString, nullptr, 1892 },//
    { "AutoSmokeParticleMediumSystem", &INI::parseAsciiString, nullptr, 1896 },//
    { "AutoSmokeParticleMediumMax", &INI::parseInt, nullptr, 1900 },//
    { "AutoSmokeParticleLargePrefix", &INI::parseAsciiString, nullptr, 1904 },//
    { "AutoSmokeParticleLargeSystem", &INI::parseAsciiString, nullptr, 1908 },//
    { "AutoSmokeParticleLargeMax", &INI::parseInt, nullptr, 1912 },//
    { "AutoAflameParticlePrefix", &INI::parseAsciiString, nullptr, 1916 },//
    { "AutoAflameParticleSystem", &INI::parseAsciiString, nullptr, 1920 },//
    { "AutoAflameParticleMax", &INI::parseInt, nullptr, 1924 },//
    { "BuildSpeed", &INI::parseReal, nullptr, 1956 },//
    { "MinDistFromEdgeOfMapForBuild", &INI::parseReal, nullptr, 1960 },//
    { "SupplyBuildBorder", &INI::parseReal, nullptr, 1964 },//
    { "AllowedHeightVariationForBuilding", &INI::parseReal, nullptr, 1968 },//
    { "MinLowEnergyProductionSpeed", &INI::parseReal, nullptr, 1972 },//
    { "MaxLowEnergyProductionSpeed", &INI::parseReal, nullptr, 1976 },//
    { "LowEnergyPenaltyModifier", &INI::parseReal, nullptr, 1980 },//
    { "MultipleFactory", &INI::parseReal, nullptr, 1984 },//
    { "RefundPercent", &INI::parsePercentToReal, nullptr, 1988 },//
    { "CommandCenterHealRange", &INI::parseReal, nullptr, 1992 },//
    { "CommandCenterHealAmount", &INI::parseReal, nullptr, 1996 },//
    { "StandardMinefieldDensity", &INI::parseReal, nullptr, 2224 },//
    { "StandardMinefieldDistance", &INI::parseReal, nullptr, 2228 },//
    { "MaxLineBuildObjects", &INI::parseInt, nullptr, 2000 },//
    { "MaxTunnelCapacity", &INI::parseInt, nullptr, 2004 },//
    { "MaxParticleCount", &INI::parseInt, nullptr, 2036 },//
    { "MaxFieldParticleCount", &INI::parseInt, nullptr, 2040 },//
    { "HorizontalScrollSpeedFactor", &INI::parseReal, nullptr, 2008 },//
    { "VerticalScrollSpeedFactor", &INI::parseReal, nullptr, 2012 },//
    { "ScrollAmountCutoff", &INI::parseReal, nullptr, 2016 },//
    { "CameraAdjustSpeed", &INI::parseReal, nullptr, 2020 },//
    { "EnforceMaxCameraHeight", &INI::parseBool, nullptr, 2024 },//
    { "KeyboardScrollSpeedFactor", &INI::parseReal, nullptr, 2080 },//
    { "KeyboardDefaultScrollSpeedFactor", &INI::parseReal, nullptr, 2084 },//
    { "MovementPenaltyDamageState", &INI::parseIndexList, &TheBodyDamageTypeNames, 2112 },//
    { "HealthBonus_Veteran", &INI::parsePercentToReal, nullptr, 2052 },//
    { "HealthBonus_Elite", &INI::parsePercentToReal, nullptr, 2056 },//
    { "HealthBonus_Heroic", &INI::parsePercentToReal, nullptr, 2060 },//
    { "HumanSoloPlayerHealthBonus_Easy", &INI::parsePercentToReal, nullptr, 1740 },//
    { "HumanSoloPlayerHealthBonus_Normal", &INI::parsePercentToReal, nullptr, 1744 },//
    { "HumanSoloPlayerHealthBonus_Hard", &INI::parsePercentToReal, nullptr, 1748 },//
    { "AISoloPlayerHealthBonus_Easy", &INI::parsePercentToReal, nullptr, 1752 },//
    { "AISoloPlayerHealthBonus_Normal", &INI::parsePercentToReal, nullptr, 1756 },//
    { "AISoloPlayerHealthBonus_Hard", &INI::parsePercentToReal, nullptr, 1760 },//
    { "WeaponBonus", &WeaponBonusSet::parseWeaponBonusSetPtr, nullptr, 2044 },//
    { "DefaultStructureRubbleHeight", &INI::parseReal, nullptr, 2064 },//
    { "FixedSeed", &INI::parseInt, nullptr, 1836 },//
    { "ShellMapName", &INI::parseAsciiString, nullptr, 2068 },//
    { "ShellMapOn", &INI::parseBool, nullptr, 2072 },//
    { "PlayIntro", &INI::parseBool, nullptr, 2073 },//
    { "FirewallBehavior", &INI::parseInt, nullptr, 1936 },//
    { "FirewallPortOverride", &INI::parseInt, nullptr, 1944 },//
    { "FirewallPortAllocationDelta", &INI::parseInt, nullptr, 1948 },//
    { "GroupSelectMinSelectSize", &INI::parseInt, nullptr, 2116 },//
    { "GroupSelectVolumeBase", &INI::parseReal, nullptr, 2120 },//
    { "GroupSelectVolumeIncrement", &INI::parseReal, nullptr, 2124 },//
    { "MaxUnitSelectSounds", &INI::parseInt, nullptr, 2128 },//
    { "SelectionFlashSaturationFactor", &INI::parseReal, nullptr, 2132 },//
    { "SelectionFlashHouseColor", &INI::parseBool, nullptr, 2136 },//
    { "CameraAudibleRadius", &INI::parseReal, nullptr, 2140 },//
    { "GroupMoveClickToGatherAreaFactor", &INI::parseReal, nullptr, 2144 },//
    { "ShakeSubtleIntensity", &INI::parseReal, nullptr, 2160 },//
    { "ShakeNormalIntensity", &INI::parseReal, nullptr, 2164 },//
    { "ShakeStrongIntensity", &INI::parseReal, nullptr, 2168 },//
    { "ShakeSevereIntensity", &INI::parseReal, nullptr, 2172 },//
    { "ShakeCineExtremeIntensity", &INI::parseReal, nullptr, 2176 },//
    { "ShakeCineInsaneIntensity", &INI::parseReal, nullptr, 2180 },//
    { "MaxShakeIntensity", &INI::parseReal, nullptr, 2184 },//
    { "MaxShakeRange", &INI::parseReal, nullptr, 2188 },//
    { "SellPercentage", &INI::parsePercentToReal, nullptr, 2192 },//
    { "BaseRegenHealthPercentPerSecond", &INI::parsePercentToReal, nullptr, 2196 },//
    { "BaseRegenDelay", &INI::parseDurationUnsignedInt, nullptr, 2200 },//
    { "SpecialPowerViewObject", &INI::parseAsciiString, nullptr, 2208 },//
    { "StandardPublicBone", &INI::parseAsciiStringVectorAppend, nullptr, 2212 },//
    { "ShowMetrics", &INI::parseBool, nullptr, 2232 },//
    { "DefaultStartingCash", &Money::parseMoneyAmount, nullptr, 2236 },//
    { "ShroudColor", &INI::parseRGBColor, nullptr, 2280 },//
    { "ClearAlpha", &INI::parseUnsignedByte, nullptr, 2292 },//
    { "FogAlpha", &INI::parseUnsignedByte, nullptr, 2293 },//
    { "ShroudAlpha", &INI::parseUnsignedByte, nullptr, 2294 },//
    { "HotKeyTextColor", &INI::parseColorInt, nullptr, 2204 },//
    { "PowerBarBase", &INI::parseInt, nullptr, 2252 },//
    { "PowerBarIntervals", &INI::parseReal, nullptr, 2256 },//
    { "PowerBarYellowRange", &INI::parseInt, nullptr, 2260 },//
    { "UnlookPersistDuration", &INI::parseDurationUnsignedInt, nullptr, 2268 },//
    { "NetworkFPSHistoryLength", &INI::parseInt, nullptr, 2296 },//
    { "NetworkLatencyHistoryLength", &INI::parseInt, nullptr, 2300 },//
    { "NetworkRunAheadMetricsTime", &INI::parseInt, nullptr, 2308 },//
    { "NetworkCushionHistoryLength", &INI::parseInt, nullptr, 2304 },//
    { "NetworkRunAheadSlack", &INI::parseInt, nullptr, 2316 },//
    { "NetworkKeepAliveDelay", &INI::parseInt, nullptr, 2312 },//
    { "NetworkDisconnectTime", &INI::parseInt, nullptr, 2320 },//
    { "NetworkPlayerTimeoutTime", &INI::parseInt, nullptr, 2324 },//
    { "NetworkDisconnectScreenNotifyTime", &INI::parseInt, nullptr, 2328 },
    { "KeyboardCameraRotateSpeed", &INI::parseReal, nullptr, 2332 },
    { "PlayStats", &INI::parseInt, nullptr, 2336 },
    { nullptr, nullptr, nullptr, 0 }
};

#endif
